age = 21
current_year = 2026
birth_year = current_year - age
print(type(age))
print("Age in 2050:", 2050 - birth_year)

x = 17
y = 5
print(x // y)  
print(x % y) 
print(x ** 2) 


birth_year = int(input("Enter your birth year: "))
age_in_2050 = 2050 - birth_year
print("Your age in the year 2050 will be:", age_in_2050)

# <class 'int'>
# Age in 2050: 45
# 3
# 2
# 289
# Enter your birth year: 2008
# Your age in the year 2050 will be: 42